"""Run the required (3+) time-series queries against the MongoDB collection.

Prints each query + its result and writes the captured output into
query_results.md (MongoDB section).

Usage:
    python mongo_queries.py
    python mongo_queries.py --start "2015-01-01" --end "2015-01-07"
"""
from __future__ import annotations

import argparse
import json
from datetime import datetime

from pymongo import ASCENDING, DESCENDING, MongoClient

from db_config import get_mongo_config, write_results_section


def _pretty(value) -> str:
    return json.dumps(value, indent=2, default=str)


def main(start: str, end: str) -> None:
    cfg = get_mongo_config()
    client = MongoClient(cfg["uri"])
    col = client[cfg["db_name"]][cfg["collection"]]

    start_dt = datetime.fromisoformat(start)
    end_dt = datetime.fromisoformat(end)

    sections = []

    # Q1 — Latest document
    q1 = "col.find_one(sort=[('datetime', DESCENDING)])"
    r1 = col.find_one(sort=[("datetime", DESCENDING)], projection={"created_at": 0})
    sections.append(("Q1 — Latest reading", q1, _pretty(r1)))

    # Q2 — Date range
    q2 = ("col.find({'datetime': {'$gte': start, '$lte': end}})"
          ".sort('datetime', ASCENDING).limit(20)")
    cur = (col.find({"datetime": {"$gte": start_dt, "$lte": end_dt}},
                    projection={"_id": 0, "datetime": 1, "consumption_mw": 1})
              .sort("datetime", ASCENDING).limit(20))
    r2 = list(cur)
    sections.append(("Q2 — Records within a date range", q2, _pretty(r2)))

    # Q3 — Average consumption by month (aggregation)
    q3 = ("col.aggregate([{'$group': {'_id': '$calendar.month', "
          "'avg_mw': {'$avg': '$consumption_mw'}, 'n': {'$sum': 1}}}, "
          "{'$sort': {'_id': 1}}])")
    r3 = list(col.aggregate([
        {"$group": {"_id": "$calendar.month",
                    "avg_mw": {"$avg": "$consumption_mw"},
                    "n": {"$sum": 1}}},
        {"$sort": {"_id": 1}},
    ]))
    for d in r3:
        d["avg_mw"] = round(d["avg_mw"], 2)
    sections.append(("Q3 — Average consumption by month (aggregation)", q3, _pretty(r3)))

    # Q4 — Peak consumption
    q4 = "col.find_one(sort=[('consumption_mw', DESCENDING)])"
    r4 = col.find_one(sort=[("consumption_mw", DESCENDING)],
                      projection={"_id": 0, "datetime": 1, "consumption_mw": 1})
    sections.append(("Q4 — Peak (maximum) consumption reading", q4, _pretty(r4)))

    client.close()

    md_sections = []
    for title, query, result in sections:
        print(f"\n=== {title} ===")
        print(query)
        print("--- result ---")
        print(result)
        md_sections.append(
            f"### {title}\n\n```python\n{query}\n```\n\n```json\n{result}\n```\n"
        )

    stamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    content = f"_Generated by mongo_queries.py at {stamp}_\n\n" + "\n".join(md_sections)
    write_results_section("MONGO_RESULTS", content)
    print("\nSaved MongoDB results to query_results.md")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Run MongoDB time-series queries")
    parser.add_argument("--start", default="2015-01-01")
    parser.add_argument("--end", default="2015-01-07")
    args = parser.parse_args()
    main(args.start, args.end)
