"""Run the required (3+) time-series queries against the MySQL star schema.

Prints each query + its result to the console, and writes the captured output
into query_results.md (SQL section) so the rubric's "show your query results"
requirement is satisfied automatically.

Usage:
    python sql_queries.py
    python sql_queries.py --start "2015-01-01" --end "2015-01-07"
"""
from __future__ import annotations

import argparse
from datetime import datetime

import mysql.connector

from db_config import get_mysql_config, write_results_section

# Each query: (title, SQL, params-builder). Kept as plain strings so they can be
# copied straight into MySQL Workbench / DBeaver as well.
QUERIES = [
    (
        "Q1 — Latest reading (JOIN across all 3 tables)",
        """
        SELECT r.region_code, d.full_datetime, f.consumption_mw
        FROM energy_readings f
        JOIN datetime_dim d ON f.datetime_id = d.datetime_id
        JOIN regions r      ON f.region_id   = r.region_id
        ORDER BY d.full_datetime DESC
        LIMIT 1;
        """,
        None,
    ),
    (
        "Q2 — Records within a date range",
        """
        SELECT d.full_datetime, f.consumption_mw
        FROM energy_readings f
        JOIN datetime_dim d ON f.datetime_id = d.datetime_id
        WHERE d.full_datetime BETWEEN %s AND %s
        ORDER BY d.full_datetime ASC
        LIMIT 20;
        """,
        "range",
    ),
    (
        "Q3 — Average consumption by month (aggregation)",
        """
        SELECT d.month, ROUND(AVG(f.consumption_mw), 2) AS avg_mw,
               COUNT(*) AS n_readings
        FROM energy_readings f
        JOIN datetime_dim d ON f.datetime_id = d.datetime_id
        GROUP BY d.month
        ORDER BY d.month;
        """,
        None,
    ),
    (
        "Q4 — Peak (maximum) consumption reading",
        """
        SELECT d.full_datetime, f.consumption_mw
        FROM energy_readings f
        JOIN datetime_dim d ON f.datetime_id = d.datetime_id
        ORDER BY f.consumption_mw DESC
        LIMIT 1;
        """,
        None,
    ),
]


def format_result(columns, rows) -> str:
    header = " | ".join(columns)
    sep = "-" * len(header)
    body = "\n".join(" | ".join(str(v) for v in row) for row in rows) or "(no rows)"
    return f"{header}\n{sep}\n{body}"


def main(start: str, end: str) -> None:
    conn = mysql.connector.connect(**get_mysql_config())
    cursor = conn.cursor()

    sections = []
    for title, sql, kind in QUERIES:
        params = (start, end) if kind == "range" else None
        cursor.execute(sql, params)
        columns = [c[0] for c in cursor.description]
        rows = cursor.fetchall()
        table = format_result(columns, rows)

        print(f"\n=== {title} ===")
        print(sql.strip())
        print("--- result ---")
        print(table)

        sections.append(
            f"### {title}\n\n```sql\n{sql.strip()}\n```\n\n```\n{table}\n```\n"
        )

    cursor.close()
    conn.close()

    stamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    content = f"_Generated by sql_queries.py at {stamp}_\n\n" + "\n".join(sections)
    write_results_section("SQL_RESULTS", content)
    print("\nSaved SQL results to query_results.md")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Run MySQL time-series queries")
    parser.add_argument("--start", default="2015-01-01 00:00:00")
    parser.add_argument("--end", default="2015-01-07 23:00:00")
    args = parser.parse_args()
    main(args.start, args.end)
